index:
    path: /
    controller: App\Controller\AccueilController::index
connexion:
    path: /connexion/{echec}/{login}
    controller: App\Controller\ConnexionController::index
    defaults:
        echec: null
        login: null
seConnecter:
    path: /seConnecter
    controller: App\Controller\ConnexionController::seConnecter
creerFiche:
    path: /creerFiche
    controller: App\Controller\CreerFicheController::index